--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tonio/Pictures/Wallpapers/Plain Fire Gradient.jpeg"

-- Special
background="#0b0b1b"
foreground="#c2c2c6"
cursor="#c2c2c6"

-- Colors
color0="#0b0b1b"
color1="#FA4F27"
color2="#FD7030"
color3="#C37746"
color4="#74836C"
color5="#DE833F"
color6="#FA8B39"
color7="#c2c2c6"
color8="#5a5a6f"
color9="#FA4F27"
color10="#FD7030"
color11="#C37746"
color12="#74836C"
color13="#DE833F"
color14="#FA8B39"
color15="#c2c2c6"
