# Shell variables
# Generated by 'wal'
wallpaper="/home/tonio/Pictures/Wallpapers/Plain Fire Gradient.jpeg"

# Special
background='#0b0b1b'
foreground='#c2c2c6'
cursor='#c2c2c6'

# Colors
color0='#0b0b1b'
color1='#FA4F27'
color2='#FD7030'
color3='#C37746'
color4='#74836C'
color5='#DE833F'
color6='#FA8B39'
color7='#c2c2c6'
color8='#5a5a6f'
color9='#FA4F27'
color10='#FD7030'
color11='#C37746'
color12='#74836C'
color13='#DE833F'
color14='#FA8B39'
color15='#c2c2c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
