[colors]
background = '#0b0b1b8e'
black = '#0b0b1b'
blue = '#FA4F27'
cursor = '#c2c2c6'
cyan = '#FD7030'
foreground = '#c2c2c6'
green = '#C37746'
magenta = '#74836C'
red = '#DE833F'
tabs = '#c2c2c6'
tabs-active = '#FA8B39'
white = '#c2c2c6'
yellow = '#c2c2c6'
dim-black = '#0b0b1b8e'
dim-blue = '#FA4F278e'
dim-cyan = '#FD70308e'
dim-foreground = '#c2c2c68e'
dim-green = '#C377468e'
dim-magenta = '#74836C8e'
dim-red = '#DE833F8e'
dim-white = '#FA8B398e'
dim-yellow = '#c2c2c68e'
light-black = '#FA4F27'
light-blue = '#FD7030'
light-cyan = '#C37746'
light-foreground = '#74836C'
light-green = '#DE833F'
light-magenta = '#FA8B39'
light-red = '#c2c2c6'
light-white = '#FA4F27'
light-yellow = '#FD7030'
