foreground         #c2c2c6
background         #0b0b1b
background_opacity 1.0
cursor             #c2c2c6

active_tab_foreground     #0b0b1b
active_tab_background     #c2c2c6
inactive_tab_foreground   #c2c2c6
inactive_tab_background   #0b0b1b

active_border_color   #c2c2c6
inactive_border_color #0b0b1b
bell_border_color     #FA4F27

color0       #0b0b1b
color8       #5a5a6f
color1       #FA4F27
color9       #FA4F27
color2       #FD7030
color10      #FD7030
color3       #C37746
color11      #C37746
color4       #74836C
color12      #74836C
color5       #DE833F
color13      #DE833F
color6       #FA8B39
color14      #FA8B39
color7       #c2c2c6
color15      #c2c2c6
