[colors.primary]
background = "#0b0b1b"
foreground = "#c2c2c6"

[colors.cursor]
text = "#0b0b1b"
cursor = "#c2c2c6"

[colors.vi_mode_cursor]
text = "#0b0b1b"
cursor = "#c2c2c6"

[colors.search.matches]
foreground = "#0b0b1b"
background = "#c2c2c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a5a6f"
background = "#c2c2c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0b1b"
red = "#FA4F27"
green = "#FD7030"
yellow = "#C37746"
blue = "#74836C"
magenta = "#DE833F"
cyan = "#FA8B39"
white = "#c2c2c6"

[colors.bright]
black = "#5a5a6f"
red = "#FA4F27"
green = "#FD7030"
yellow = "#C37746"
blue = "#74836C"
magenta = "#DE833F"
cyan = "#FA8B39"
white = "#c2c2c6"

[colors.dim]
black = "#c2c2c6"
red = "#FA4F27"
green = "#DE833F"
yellow = "#C37746"
blue = "#74836C"
magenta = "#FD7030"
cyan = "#FA8B39"
white = "#5a5a6f"

