$wallpaper = {{image}}
$text_color = rgb({{colors.on_background.default.hex | replace: "#", ""}})
$entry_background_color = rgb({{colors.background.default.hex | replace: "#", ""}})
$entry_border_color = rgb({{colors.primary.default.hex | replace: "#", ""}})
$entry_color = rgb({{colors.primary.default.hex | replace: "#", ""}})
